// Command gennames reads metric-names.yaml and emits matching Go
// constants and LaTeX commands for the book.
//
// Run via `make gen-names`. CI also runs this and verifies the
// generated files have no diff, so PR authors can't forget to
// regenerate after editing the YAML.
//
// The tool exists because OTel metric/attribute/label names are
// referenced in code, chapter prose, dashboards, alert rules, and
// PromQL queries. Drift between any of those is silently corrosive
// -- the chapter says X, the metric is named Y, the dashboard returns
// nothing. Code-gen from one source eliminates the failure mode.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

var (
	yamlPath = flag.String("yaml", "metric-names.yaml", "input YAML schema")
	goOut    = flag.String("go-out", "internal/telemetry/names.go", "output path for Go constants")
	texOut   = flag.String("tex-out", "../book/src/styles/metric-names.tex", "output path for LaTeX commands")
)

// Entry is one named value in the schema.
type Entry struct {
	Key         string `yaml:"key"`
	Value       string `yaml:"value"`
	Description string `yaml:"description,omitempty"`
}

// Schema is the top-level YAML structure.
type Schema struct {
	Metrics              []Entry `yaml:"metrics"`
	InferenceAttributes  []Entry `yaml:"inference_attributes"`
	DeploymentAttributes []Entry `yaml:"deployment_attributes"`
	Labels               []Entry `yaml:"labels"`
}

func main() {
	flag.Parse()

	raw, err := os.ReadFile(*yamlPath)
	if err != nil {
		die("read schema: %v", err)
	}
	var schema Schema
	if err := yaml.Unmarshal(raw, &schema); err != nil {
		die("parse schema: %v", err)
	}

	// Stable order so generated files don't churn from YAML reorders.
	for _, group := range [][]Entry{schema.Metrics, schema.InferenceAttributes, schema.DeploymentAttributes, schema.Labels} {
		sort.Slice(group, func(i, j int) bool { return group[i].Key < group[j].Key })
	}

	if err := writeGo(*goOut, schema); err != nil {
		die("write Go: %v", err)
	}
	if err := writeTex(*texOut, schema); err != nil {
		die("write tex: %v", err)
	}

	fmt.Fprintf(os.Stderr, "gennames: wrote %s and %s\n", *goOut, *texOut)
}

// writeGo emits the Go constants file.
func writeGo(path string, s Schema) error {
	tmpl := template.Must(template.New("go").Funcs(template.FuncMap{
		"exported": exported,
	}).Parse(goTemplate))
	return renderTo(path, tmpl, s)
}

// writeTex emits the LaTeX commands file. Tex-special characters in
// values are escaped (the most common one we hit is `_`).
func writeTex(path string, s Schema) error {
	tmpl := template.Must(template.New("tex").Funcs(template.FuncMap{
		"exported": exported,
		"camel":    camel,
		"texValue": texEscape,
	}).Parse(texTemplate))
	return renderTo(path, tmpl, s)
}

func renderTo(path string, tmpl *template.Template, s Schema) error {
	var buf strings.Builder
	if err := tmpl.Execute(&buf, s); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(buf.String()), 0644)
}

// exported converts a snake_case key into ExportedCamelCase (for Go
// constants). "request_duration" -> "RequestDuration".
func exported(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Special-case all-caps acronyms we've used (id, gpu).
		switch p {
		case "id":
			b.WriteString("ID")
			continue
		case "gpu":
			b.WriteString("GPU")
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// camel converts snake_case to lowerCamelCase (for tex command names).
// "request_duration" -> "requestDuration".
func camel(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for i, p := range parts {
		if p == "" {
			continue
		}
		if i == 0 {
			b.WriteString(p)
			continue
		}
		switch p {
		case "id":
			b.WriteString("ID")
			continue
		case "gpu":
			b.WriteString("GPU")
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// texEscape escapes the LaTeX-special characters we actually encounter
// in metric/attribute values. The value goes inside \newcommand{}{...},
// where the body is reprocessed at expansion time -- so unescaped
// underscores trigger math-mode errors.
func texEscape(s string) string {
	r := strings.NewReplacer(
		`\`, `\textbackslash{}`,
		`_`, `\_`,
		`&`, `\&`,
		`%`, `\%`,
		`#`, `\#`,
		`$`, `\$`,
		`{`, `\{`,
		`}`, `\}`,
		`~`, `\textasciitilde{}`,
		`^`, `\textasciicircum{}`,
	)
	return r.Replace(s)
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gennames: "+format+"\n", args...)
	os.Exit(1)
}

const goTemplate = `// Code generated by cmd/gennames; DO NOT EDIT.
// Source: metric-names.yaml
//
// Run ` + "`make gen-names`" + ` to regenerate after editing the schema.
// Run ` + "`make check-names`" + ` (CI does this) to fail-fast if the schema
// has been edited without regenerating.

package telemetry

// Metric instrument names emitted by the control plane.
{{range .Metrics}}
// Metric{{exported .Key}} -- {{.Description}}
const Metric{{exported .Key}} = {{printf "%q" .Value}}
{{end}}

// Inference span and resource attribute keys.
const (
{{- range .InferenceAttributes}}
	AttrInference{{exported .Key}} = {{printf "%q" .Value}}
{{- end}}
)

// Deployment-identity resource attribute keys. These describe which
// provider/gpu_type/billing_mode/instance_id this control plane is
// running on, attached to every span and metric as resource attributes.
const (
{{- range .DeploymentAttributes}}
	AttrDeployment{{exported .Key}} = {{printf "%q" .Value}}
{{- end}}
)

// Metric label keys (the dimensions on counter/histogram/gauge instruments).
const (
{{- range .Labels}}
	Label{{exported .Key}} = {{printf "%q" .Value}}
{{- end}}
)
`

const texTemplate = `%% Auto-generated by cmd/gennames in the inference_plane repo;
%% DO NOT EDIT BY HAND. Run ` + "`make gen-names`" + ` to regenerate.
%% Source: inference_plane/metric-names.yaml

%% Metric instrument names.
{{range .Metrics -}}
\newcommand{\metric{{exported .Key}}}{ {{- texValue .Value -}} }
{{end}}
%% Inference span/resource attribute keys.
{{range .InferenceAttributes -}}
\newcommand{\attrInference{{exported .Key}}}{ {{- texValue .Value -}} }
{{end}}
%% Deployment-identity resource attribute keys.
{{range .DeploymentAttributes -}}
\newcommand{\attrDeployment{{exported .Key}}}{ {{- texValue .Value -}} }
{{end}}
%% Metric label keys.
{{range .Labels -}}
\newcommand{\label{{exported .Key}}}{ {{- texValue .Value -}} }
{{end}}`
