package server

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/inference-book/inference-plane/internal/backend"
)

// mockBackend is a Backend implementation whose methods are pluggable
// per-test. Lets each test case shape the upstream behavior precisely
// without spinning up an httptest server.
type mockBackend struct {
	name     string
	generate func(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error)
	health   func(ctx context.Context) error
}

func (m *mockBackend) Name() string { return m.name }
func (m *mockBackend) Generate(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error) {
	return m.generate(ctx, req)
}
func (m *mockBackend) Health(ctx context.Context) error {
	if m.health == nil {
		return nil
	}
	return m.health(ctx)
}

// silentLogger discards log output; we don't want test output cluttered
// with structured logs from the handler's error paths.
var silentLogger = slog.New(slog.NewTextHandler(io.Discard, nil))

// validReq is a minimal valid completion request used as the default
// payload; tests override fields as needed.
func validReq() backend.GenerateRequest {
	return backend.GenerateRequest{Model: "qwen", Prompt: "hello", MaxTokens: 4}
}

func okResp() backend.GenerateResponse {
	return backend.GenerateResponse{
		ID: "x", Object: "text_completion", Model: "qwen",
		Choices: []backend.Choice{{Index: 0, Text: "world", FinishReason: "stop"}},
		Usage:   backend.Usage{PromptTokens: 1, CompletionTokens: 1, TotalTokens: 2},
	}
}

// callHandler sends a synthetic request to a handler and returns the
// recorded response. Body is JSON-encoded from the supplied any (or
// passed through if it's a string -- used for malformed-JSON cases).
func callHandler(t *testing.T, h http.Handler, method, path string, body any) *httptest.ResponseRecorder {
	t.Helper()
	var bodyReader io.Reader
	switch v := body.(type) {
	case nil:
	case string:
		bodyReader = strings.NewReader(v)
	default:
		raw, err := json.Marshal(v)
		if err != nil {
			t.Fatalf("marshal request body: %v", err)
		}
		bodyReader = strings.NewReader(string(raw))
	}
	req := httptest.NewRequest(method, path, bodyReader)
	w := httptest.NewRecorder()
	h.ServeHTTP(w, req)
	return w
}

// ── Happy path ─────────────────────────────────────────────────────

func TestHandler_PlainCompletion_OK(t *testing.T) {
	be := &mockBackend{
		name: "test",
		generate: func(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error) {
			if req.Prompt != "hello" {
				t.Errorf("backend got wrong prompt: %q", req.Prompt)
			}
			return okResp(), nil
		},
	}
	h := &completionsHandler{backend: be, logger: silentLogger}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", validReq())

	if w.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", w.Code)
	}
	var out backend.GenerateResponse
	if err := json.Unmarshal(w.Body.Bytes(), &out); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if out.Choices[0].Text != "world" {
		t.Errorf("response text = %q, want 'world'", out.Choices[0].Text)
	}
}

// ── Validation failures (4xx generated by the handler itself) ─────

func TestHandler_RejectsNonPost(t *testing.T) {
	h := &completionsHandler{backend: nil, logger: silentLogger}
	w := callHandler(t, h, http.MethodGet, "/v1/completions", nil)
	if w.Code != http.StatusMethodNotAllowed {
		t.Errorf("status = %d, want 405", w.Code)
	}
}

func TestHandler_RejectsMalformedJSON(t *testing.T) {
	h := &completionsHandler{backend: nil, logger: silentLogger}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", "{not json")
	if w.Code != http.StatusBadRequest {
		t.Errorf("status = %d, want 400", w.Code)
	}
}

func TestHandler_RejectsMissingModel(t *testing.T) {
	h := &completionsHandler{backend: nil, logger: silentLogger}
	req := validReq()
	req.Model = ""
	w := callHandler(t, h, http.MethodPost, "/v1/completions", req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("status = %d, want 400", w.Code)
	}
}

func TestHandler_RejectsEmptyPromptAndMessages(t *testing.T) {
	h := &completionsHandler{backend: nil, logger: silentLogger}
	req := validReq()
	req.Prompt = ""
	w := callHandler(t, h, http.MethodPost, "/v1/completions", req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("status = %d, want 400", w.Code)
	}
}

func TestHandler_RejectsBothPromptAndMessages(t *testing.T) {
	h := &completionsHandler{backend: nil, logger: silentLogger}
	req := validReq()
	req.Messages = []backend.ChatMessage{{Role: "user", Content: "hi"}}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", req)
	if w.Code != http.StatusBadRequest {
		t.Errorf("status = %d, want 400", w.Code)
	}
}

// ── Backend error mapping (Chapter 6.5 rules) ──────────────────────

// 4xx upstream passes through to the client unchanged. The body the
// upstream sent (e.g. a token-limit message) is forwarded so the client
// gets actionable detail.
func TestHandler_Backend4xx_PassesThrough(t *testing.T) {
	be := &mockBackend{
		generate: func(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error) {
			return backend.GenerateResponse{}, &backend.BackendError{
				Backend: "vllm", StatusCode: 422, Body: "context length exceeded",
			}
		},
	}
	h := &completionsHandler{backend: be, logger: silentLogger}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", validReq())

	if w.Code != 422 {
		t.Errorf("status = %d, want 422", w.Code)
	}
	if !strings.Contains(w.Body.String(), "context length exceeded") {
		t.Errorf("expected upstream body to pass through, got: %s", w.Body.String())
	}
}

// 5xx upstream becomes 502 to the client. The original body is logged
// (we asserted that elsewhere via writeBackendError) but not surfaced
// to the client -- it's an internal detail.
func TestHandler_Backend5xx_BecomesBadGateway(t *testing.T) {
	be := &mockBackend{
		generate: func(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error) {
			return backend.GenerateResponse{}, &backend.BackendError{
				Backend: "vllm", StatusCode: 503, Body: "overloaded",
			}
		},
	}
	h := &completionsHandler{backend: be, logger: silentLogger}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", validReq())

	if w.Code != http.StatusBadGateway {
		t.Errorf("status = %d, want 502", w.Code)
	}
}

// Context cancellation surfaces as 499 (client closed request). Lets
// metrics distinguish caller-cancelled work from real backend failures.
func TestHandler_ContextCancelled_BecomesClientClosed(t *testing.T) {
	be := &mockBackend{
		generate: func(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error) {
			return backend.GenerateResponse{}, context.Canceled
		},
	}
	h := &completionsHandler{backend: be, logger: silentLogger}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", validReq())

	if w.Code != 499 {
		t.Errorf("status = %d, want 499", w.Code)
	}
}

// Anything else (network failure, decode failure, plain error) becomes
// a 502: we don't know enough to be more specific, but we know it's an
// upstream-side problem.
func TestHandler_GenericError_BecomesBadGateway(t *testing.T) {
	be := &mockBackend{
		generate: func(ctx context.Context, req backend.GenerateRequest) (backend.GenerateResponse, error) {
			return backend.GenerateResponse{}, errors.New("network unreachable")
		},
	}
	h := &completionsHandler{backend: be, logger: silentLogger}
	w := callHandler(t, h, http.MethodPost, "/v1/completions", validReq())

	if w.Code != http.StatusBadGateway {
		t.Errorf("status = %d, want 502", w.Code)
	}
}
