// Code generated by iplane gen-names; DO NOT EDIT.
// Source: metric-names.yaml
//
// Run `make gen-names` to regenerate after editing the schema.
// Run `make check-names` (CI does this) to fail-fast if the schema
// has been edited without regenerating.

package telemetry

// Metric instrument names emitted by the control plane.

// MetricBackendHealthy -- Gauge -- 1 if backend is healthy, 0 otherwise. Feeds alerts.
const MetricBackendHealthy = "inference.backend.healthy"

// MetricDeploymentPhaseDuration -- Histogram of seconds spent in each deployment lifecycle phase (scheduling, image-pull, engine-init, ...), labeled by phase / provider / result / storage_tier. Splits the opaque cold-start into attributable stages so model-download and image-pull time are separable; storage_tier (cold=HF download in-pod, warm=pre-staged volume mount) makes the engine-init collapse of a warm deploy visible against a cold one (Ch 9).
const MetricDeploymentPhaseDuration = "iplane.deployment.phase.duration"

// MetricDeploymentProvisionDuration -- Histogram of end-to-end deployment provision wall-clock seconds (create-pod through engine serving), labeled by provider / result / class / storage_tier. The "why is my deploy slow" top-line for the deployment dashboard; storage_tier (cold=HF download in-pod, warm=pre-staged volume mount) is the Ch 9 cold-start-distance cut.
const MetricDeploymentProvisionDuration = "iplane.deployment.provision.duration"

// MetricDeploymentProvisionsTotal -- Counter of deployment provision attempts, labeled by provider / result (running, failed, timeout). Denominator for the provision success-rate panel.
const MetricDeploymentProvisionsTotal = "iplane.deployment.provisions.total"

// MetricDeploymentTeardownDuration -- Histogram of deployment teardown wall-clock seconds (destroy through terminated), labeled by provider / result. The spin-down half of the lifecycle dashboard; pairs with iplane.reaper.destroys.total.
const MetricDeploymentTeardownDuration = "iplane.deployment.teardown.duration"

// MetricGPUEffectiveRate -- Gauge of per-second cost rate for each provider/gpu_type/billing_mode combination loaded from providers.yaml. One series per provider for the cross-provider cost-projection panel.
const MetricGPUEffectiveRate = "gpu.effective_rate.usd_per_second"

// MetricInferenceActiveSeconds -- Counter of seconds spent actively serving inference, labeled by the instance that served them. Divided by instance.uptime it gives utilization, and the gap between the two is what idle capacity costs.
const MetricInferenceActiveSeconds = "inference.active.seconds.total"

// MetricInstanceCost -- Counter of dollars spent per rented instance, the product of the billed seconds and the rate the provider quoted at spawn. The uptime counter and the rate gauge publish those two factors separately, and this series publishes what they multiply to, so a cost figure no longer has to be assembled by hand. An instance whose provider reported no rate is omitted rather than reported as zero, because zero and unknown are not the same bill. Cost per million tokens divides this by the token counter, which carries the same instance_id: increase(instance_cost_usd_total[w]) / increase(inference_tokens_generated[w]) * 1e6. That ratio has to be windowed rather than cumulative. A lifetime average smears every concurrency level together, and the curve across those levels is what Part IV measures.
const MetricInstanceCost = "instance.cost.usd.total"

// MetricInstanceRate -- Gauge of the per-second price of one rented instance, from the rate the provider quoted at spawn. Joins instance.uptime on instance_id to give spend, which is the figure a cost argument is actually made from. Distinct from gpu.effective_rate, which prices the catalog rather than the fleet.
const MetricInstanceRate = "instance.rate.usd_per_second"

// MetricInstanceUptimeSeconds -- Counter of billed seconds per rented instance, measured from when the provider said it was active. One series per instance, labeled by instance_id / provider / gpu_type / billing_mode. Was previously the daemon's own uptime under one asserted label set, which described the control plane rather than anything being paid for.
const MetricInstanceUptimeSeconds = "instance.uptime.seconds.total"

// MetricQueueDepth -- Gauge of current items waiting in the router's per-(deploy, tenant, lane) sub-queue. Updated synchronously on push/pop. Operator-facing signal for fair-share visibility (v0.2 ch7-beat2.6).
const MetricQueueDepth = "iplane.queue.depth"

// MetricQueueWaitSeconds -- Histogram of seconds an entry spent waiting in the router's queue before dispatch. Labeled by deploy_id / tenant_id / class so per-class p95 wait is the chapter's fair-queueing dashboard story.
const MetricQueueWaitSeconds = "iplane.queue.wait.seconds"

// MetricReaperDestroysTotal -- Counter of deployments destroyed by the idle-TTL reaper, labeled by reason (idle, etc.). Operator-facing signal of leak protection working.
const MetricReaperDestroysTotal = "iplane.reaper.destroys.total"

// MetricReplicaInFlight -- Synchronous gauge of current in-flight requests per (deploy_id, instance_id). Emitted on dispatch + on response so the value tracks live load. Demo 06's "watch replicas equalize under round-robin" panel reads this (v0.2 ch7-beat3.6,
const MetricReplicaInFlight = "iplane.replica.in_flight"

// MetricRequestDuration -- Histogram of request duration in seconds. Bucket edges tuned for the bimodal LLM latency distribution (Chapter 6.6.4).
const MetricRequestDuration = "inference.request.duration"

// MetricRequestsTotal -- Counter of inference requests, labeled by model and status.
const MetricRequestsTotal = "inference.requests.total"

// MetricRouterAffinityTotal -- Counter of session-affinity outcomes, labeled by deploy_id / outcome. For each request carrying X-IPlane-Session, the router compares the chosen replica against where that session last landed -- "hit" when it matches (the session's prefix is where it was left), "miss" when it moved or was first-seen. The hit-rate = hit / (hit + miss) is the Ch 8 money panel -- round-robin scatters sessions so it sits near 1/N, prefix_affinity pins them so it climbs toward 1.0. A routing-locality signal measured at the router; a faithful proxy for the engine's own gpu_prefix_cache_hit_rate (which iplane can't see without scraping the engine, issue
const MetricRouterAffinityTotal = "iplane.router.affinity.total"

// MetricRouterDecisionsTotal -- Counter of routing decisions, labeled by deploy_id / instance_id / outcome. Outcomes -- "picked" when a replica was selected, "no_replicas" when all were empty/quarantined (the 503 replica_unavailable path). Complementary to inference.requests.total which counts completed requests with downstream status (v0.2 ch7-beat3.6,
const MetricRouterDecisionsTotal = "iplane.router.decisions.total"

// MetricTokensGenerated -- Counter of tokens generated. The right load metric for LLM workloads, since it correlates with cost in a way request count never can. Labeled by context_bucket, an upper-bound band on the prompt length read off the engine's usage block, because cost per token depends on context length and two runs at different context lengths are not the same measurement. A response reporting no prompt count lands in the "unknown" band rather than in the shortest one.
const MetricTokensGenerated = "inference.tokens.generated"


// Inference span and resource attribute keys.
const (
	AttrInferenceCompletionTokens = "inference.completion_tokens"
	AttrInferenceFinishReason = "inference.finish_reason"
	AttrInferenceMaxTokens = "inference.max_tokens"
	AttrInferenceModel = "inference.model"
	AttrInferencePromptTokens = "inference.prompt_tokens"
	AttrInferenceTotalTokens = "inference.total_tokens"
)

// Deployment-identity resource attribute keys. These describe which
// provider/gpu_type/billing_mode/instance_id this control plane is
// running on, attached to every span and metric as resource attributes.
const (
	AttrDeploymentBillingMode = "deployment.billing_mode"
	AttrDeploymentGPUType = "deployment.gpu_type"
	AttrDeploymentInstanceID = "deployment.instance_id"
	AttrDeploymentProvider = "deployment.provider"
)

// Metric label keys (the dimensions on counter/histogram/gauge instruments).
const (
	LabelBillingMode = "billing_mode"
	LabelClass = "class"
	LabelContextBucket = "context_bucket"
	LabelDeployID = "deploy_id"
	LabelGPUType = "gpu_type"
	LabelInstanceID = "instance_id"
	LabelModel = "model"
	LabelOutcome = "outcome"
	LabelPhase = "phase"
	LabelPriority = "priority"
	LabelProvider = "provider"
	LabelReason = "reason"
	LabelResult = "result"
	LabelStatus = "status"
	LabelStorageTier = "storage_tier"
	LabelTenantID = "tenant_id"
)
