// Code generated by iplane gen-names; DO NOT EDIT.
// Source: metric-names.yaml
//
// Run `make gen-names` to regenerate after editing the schema.
// Run `make check-names` (CI does this) to fail-fast if the schema
// has been edited without regenerating.

package telemetry

// Metric instrument names emitted by the control plane.

// MetricBackendHealthy -- Gauge -- 1 if backend is healthy, 0 otherwise. Feeds alerts.
const MetricBackendHealthy = "inference.backend.healthy"

// MetricGPUEffectiveRate -- Gauge of per-second cost rate for each provider/gpu_type/billing_mode combination loaded from providers.yaml. One series per provider for the cross-provider cost-projection panel.
const MetricGPUEffectiveRate = "gpu.effective_rate.usd_per_second"

// MetricInferenceActiveSeconds -- Counter of seconds spent actively serving inference. Combined with instance.uptime gives utilization.
const MetricInferenceActiveSeconds = "inference.active.seconds.total"

// MetricInstanceUptimeSeconds -- Counter of wall-clock seconds since the control plane started. Base for billed-time cost calculations.
const MetricInstanceUptimeSeconds = "instance.uptime.seconds.total"

// MetricQueueDepth -- Gauge of current items waiting in the router's per-(deploy, tenant, lane) sub-queue. Updated synchronously on push/pop. Operator-facing signal for fair-share visibility (v0.2 ch7-beat2.6).
const MetricQueueDepth = "iplane.queue.depth"

// MetricQueueWaitSeconds -- Histogram of seconds an entry spent waiting in the router's queue before dispatch. Labeled by deploy_id / tenant_id / class so per-class p95 wait is the chapter's fair-queueing dashboard story.
const MetricQueueWaitSeconds = "iplane.queue.wait.seconds"

// MetricReaperDestroysTotal -- Counter of deployments destroyed by the idle-TTL reaper, labeled by reason (idle, etc.). Operator-facing signal of leak protection working.
const MetricReaperDestroysTotal = "iplane.reaper.destroys.total"

// MetricRequestDuration -- Histogram of request duration in seconds. Bucket edges tuned for the bimodal LLM latency distribution (Chapter 6.6.4).
const MetricRequestDuration = "inference.request.duration"

// MetricRequestsTotal -- Counter of inference requests, labeled by model and status.
const MetricRequestsTotal = "inference.requests.total"

// MetricTokensGenerated -- Counter of tokens generated. The right load metric for LLM workloads -- correlates with cost in a way request count never can.
const MetricTokensGenerated = "inference.tokens.generated"


// Inference span and resource attribute keys.
const (
	AttrInferenceCompletionTokens = "inference.completion_tokens"
	AttrInferenceFinishReason = "inference.finish_reason"
	AttrInferenceMaxTokens = "inference.max_tokens"
	AttrInferenceModel = "inference.model"
	AttrInferencePromptTokens = "inference.prompt_tokens"
	AttrInferenceTotalTokens = "inference.total_tokens"
)

// Deployment-identity resource attribute keys. These describe which
// provider/gpu_type/billing_mode/instance_id this control plane is
// running on, attached to every span and metric as resource attributes.
const (
	AttrDeploymentBillingMode = "deployment.billing_mode"
	AttrDeploymentGPUType = "deployment.gpu_type"
	AttrDeploymentInstanceID = "deployment.instance_id"
	AttrDeploymentProvider = "deployment.provider"
)

// Metric label keys (the dimensions on counter/histogram/gauge instruments).
const (
	LabelBillingMode = "billing_mode"
	LabelDeployID = "deploy_id"
	LabelGPUType = "gpu_type"
	LabelModel = "model"
	LabelPriority = "priority"
	LabelProvider = "provider"
	LabelReason = "reason"
	LabelReplicaID = "replica_id"
	LabelStatus = "status"
	LabelTenantID = "tenant_id"
)
