// Package metrics holds the OTel meter instruments emitted by the
// control plane and helpers that record into them. The instruments
// are constructed once at startup (NewRecorder) via the global
// MeterProvider that telemetry.Init registered.
//
// Two recorders live here: Recorder for the four application metric
// families from chapter 6.6.2, and CostRecorder for the cost
// economics metrics from the chapter's cost-tracking subsection.
// They're separate because they have different lifecycles -- the
// application metrics emit per-request from handlers; the cost
// metrics emit periodically (uptime) or per-deployment (rates).
package metrics

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	"github.com/inference-book/inference-plane/internal/telemetry"
)

// Recorder holds the four application metric instruments from
// Chapter 6.6.2 and exposes record* helpers that handlers call.
//
// Constructed once at startup; passed by pointer to handlers and
// services that need to emit metrics. nil-safe at the call site so
// tests that don't init telemetry still work (no-op recorder).
type Recorder struct {
	requests       metric.Int64Counter
	duration       metric.Float64Histogram
	tokens         metric.Int64Counter
	backendHealthy metric.Int64Gauge
	reaperDestroys metric.Int64Counter
	queueDepth     metric.Int64Gauge
	queueWait      metric.Float64Histogram
}

// NewRecorder builds the four instruments via the global MeterProvider.
// telemetry.Init must have run first; otherwise the instruments come
// from the no-op MeterProvider and emissions go nowhere (which is
// fine for tests).
//
// Errors building any single instrument are returned -- a partial
// Recorder is more confusing than a failure during startup, and the
// instruments are simple enough that any failure is a real bug worth
// surfacing immediately.
func NewRecorder() (*Recorder, error) {
	meter := otel.Meter("inference-plane/metrics")

	requests, err := meter.Int64Counter(
		telemetry.MetricRequestsTotal,
		metric.WithDescription("Inference requests, labeled by model and status."),
		metric.WithUnit("{request}"),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: requests counter: %w", err)
	}

	// Bucket edges from Chapter 6.6.4. The bimodal LLM latency
	// distribution -- short cached prompts at one end, long
	// generations at the other -- needs both ends resolved. Wrongly-
	// chosen buckets pile most requests into one bucket and percentiles
	// become meaningless.
	duration, err := meter.Float64Histogram(
		telemetry.MetricRequestDuration,
		metric.WithDescription("Request duration in seconds (bimodal LLM latency)."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.1, 0.5, 1, 2, 5, 10, 30, 60),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: duration histogram: %w", err)
	}

	tokens, err := meter.Int64Counter(
		telemetry.MetricTokensGenerated,
		metric.WithDescription("Tokens generated by inference. The right load metric for LLM workloads."),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: tokens counter: %w", err)
	}

	healthy, err := meter.Int64Gauge(
		telemetry.MetricBackendHealthy,
		metric.WithDescription("Backend health, 1=healthy / 0=unhealthy. Feeds alerts."),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: health gauge: %w", err)
	}

	reaperDestroys, err := meter.Int64Counter(
		telemetry.MetricReaperDestroysTotal,
		metric.WithDescription("Deployments destroyed by the idle-TTL reaper, labeled by reason."),
		metric.WithUnit("{deployment}"),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: reaper counter: %w", err)
	}

	queueDepth, err := meter.Int64Gauge(
		telemetry.MetricQueueDepth,
		metric.WithDescription("Current items waiting in the router's per-(deploy, tenant, lane) sub-queue."),
		metric.WithUnit("{request}"),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: queue depth gauge: %w", err)
	}

	// Wait-time histogram buckets cover the operator-observable
	// spectrum: sub-second (interactive p50), a few seconds (under
	// queue pressure), tens of seconds (saturated batch). Same
	// shape as the request-duration histogram so dashboards can
	// stack the two for the chapter's queue-vs-engine-time
	// breakdown.
	queueWait, err := meter.Float64Histogram(
		telemetry.MetricQueueWaitSeconds,
		metric.WithDescription("Seconds an entry spent waiting in the router's queue before dispatch."),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.001, 0.01, 0.1, 0.5, 1, 2, 5, 10, 30),
	)
	if err != nil {
		return nil, fmt.Errorf("metrics: queue wait histogram: %w", err)
	}

	return &Recorder{
		requests:       requests,
		duration:       duration,
		tokens:         tokens,
		backendHealthy: healthy,
		reaperDestroys: reaperDestroys,
		queueDepth:     queueDepth,
		queueWait:      queueWait,
	}, nil
}

// RecordRequest emits one observation of the requests counter and the
// duration histogram. status is the outcome label: "success",
// "client_error", "backend_error", "client_closed", etc. The same
// model+status combination shows up on both instruments so a single
// PromQL query can break out either dimension.
//
// nil-safe: a handler holding a nil Recorder (in tests, e.g.) gets a
// no-op rather than a panic.
func (r *Recorder) RecordRequest(ctx context.Context, model, status string, durationSec float64) {
	if r == nil {
		return
	}
	attrs := metric.WithAttributes(
		attribute.String(telemetry.LabelModel, model),
		attribute.String(telemetry.LabelStatus, status),
	)
	r.requests.Add(ctx, 1, attrs)
	r.duration.Record(ctx, durationSec, attrs)
}

// RecordTokens adds n to the tokens-generated counter for the given
// model. Tracking only completion tokens here (not prompt tokens) --
// prompt-token detail is on the trace span; the aggregate cost-relevant
// signal is what the model produced.
func (r *Recorder) RecordTokens(ctx context.Context, model string, n int64) {
	if r == nil || n <= 0 {
		return
	}
	r.tokens.Add(ctx, n, metric.WithAttributes(
		attribute.String(telemetry.LabelModel, model),
	))
}

// SetBackendHealth records the current backend health into the gauge.
// Called from the /health probe path on every probe.
func (r *Recorder) SetBackendHealth(ctx context.Context, healthy bool) {
	if r == nil {
		return
	}
	v := int64(0)
	if healthy {
		v = 1
	}
	r.backendHealthy.Record(ctx, v)
}

// RecordRouterRequest emits the request-rate counter and the
// duration histogram for one inference request that flowed through
// the v0.2 data-plane router. Reuses the v0.1 instruments
// (inference.requests.total, inference.request.duration) so existing
// dashboards and alert rules see the new traffic alongside any
// remaining v0.1 emissions; the label set extends with deploy_id and
// tenant_id so the router's flow can be filtered out separately.
//
// tenantID is the optional v0.2 Beat-2 scaffold field. v0.2 Beat-1
// emits an empty string here so the label cardinality stays at one
// value until Beat 2 wires per-tenant identification through the
// router.
//
// status is the outcome label, mirroring RecordRequest's convention:
// "success", "client_error", "backend_error", "client_closed", etc.
//
// nil-safe: handlers that hold a nil Recorder (tests, daemon
// constructed without telemetry init) get a no-op rather than a
// panic.
func (r *Recorder) RecordRouterRequest(ctx context.Context, deployID, model, tenantID, priority, replicaID, status string, durationSec float64) {
	if r == nil {
		return
	}
	attrs := metric.WithAttributes(
		attribute.String(telemetry.LabelDeployID, deployID),
		attribute.String(telemetry.LabelModel, model),
		attribute.String(telemetry.LabelTenantID, tenantID),
		attribute.String(telemetry.LabelPriority, priority),
		attribute.String(telemetry.LabelReplicaID, replicaID),
		attribute.String(telemetry.LabelStatus, status),
	)
	r.requests.Add(ctx, 1, attrs)
	r.duration.Record(ctx, durationSec, attrs)
}

// RecordReaperDestroy bumps the reaper-destroys counter for a single
// reap event. reason labels the cause -- "idle" for idle-TTL expiry,
// "explicit" if a future cost-aware sweep adds richer reasons.
//
// nil-safe so daemons constructed without telemetry init (some test
// harnesses) get a no-op rather than a panic.
func (r *Recorder) RecordReaperDestroy(ctx context.Context, reason string) {
	if r == nil {
		return
	}
	r.reaperDestroys.Add(ctx, 1, metric.WithAttributes(
		attribute.String(telemetry.LabelReason, reason),
	))
}

// RecordRouterTokens adds n to the tokens-generated counter for a
// router-mediated inference, labeled by deploy_id / model / tenant_id.
// Same instrument as RecordTokens; the extra labels make the router's
// contribution distinguishable from v0.1 inference-service emissions.
//
// Skip calling this when n is zero or unknown (e.g., a streaming
// request whose engine did not emit a `usage` frame) -- recording
// zeros pollutes the counter without adding signal.
func (r *Recorder) RecordRouterTokens(ctx context.Context, deployID, model, tenantID, priority, replicaID string, n int64) {
	if r == nil || n <= 0 {
		return
	}
	r.tokens.Add(ctx, n, metric.WithAttributes(
		attribute.String(telemetry.LabelDeployID, deployID),
		attribute.String(telemetry.LabelModel, model),
		attribute.String(telemetry.LabelTenantID, tenantID),
		attribute.String(telemetry.LabelPriority, priority),
		attribute.String(telemetry.LabelReplicaID, replicaID),
	))
}

// RecordQueueDepth emits one observation of the queue-depth gauge
// for the (deploy_id, tenant_id, priority) cell. Called by the
// scheduler observer on every push + pop so the dashboard sees
// live depth changes.
//
// Synchronous gauge (not async/observable) because the scheduler
// already owns the source of truth and emits cheaply; a callback-
// based observable gauge would need a periodic scrape of the same
// state with no operator-visible difference.
//
// nil-safe.
func (r *Recorder) RecordQueueDepth(ctx context.Context, deployID, tenantID, priority string, depth int64) {
	if r == nil {
		return
	}
	r.queueDepth.Record(ctx, depth, metric.WithAttributes(
		attribute.String(telemetry.LabelDeployID, deployID),
		attribute.String(telemetry.LabelTenantID, tenantID),
		attribute.String(telemetry.LabelPriority, priority),
	))
}

// RecordQueueWait records one wait-duration observation in the
// queue-wait histogram. Called by the scheduler observer when an
// entry exits the queue. Zero / negative durations are dropped --
// they indicate the entry came from an Entry impl that doesn't
// stamp enqueue time (test no-ops) and recording them would skew
// the histogram toward 0.
//
// nil-safe.
func (r *Recorder) RecordQueueWait(ctx context.Context, deployID, tenantID, priority string, waitSec float64) {
	if r == nil || waitSec <= 0 {
		return
	}
	r.queueWait.Record(ctx, waitSec, metric.WithAttributes(
		attribute.String(telemetry.LabelDeployID, deployID),
		attribute.String(telemetry.LabelTenantID, tenantID),
		attribute.String(telemetry.LabelPriority, priority),
	))
}
